project:
  type: website
  resources:
    - files/ActingResume7-8.pdf
  output-dir: docs

website:
  title: "Raine Higa"
  site-url: https://www.rainehiga.com
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Reels"
        href: reels.qmd
	

format:
  html:
    theme: trestles
    css: styles.css
    toc: true
