project:
  type: website
  output-dir: docs

website:
  title: "rainehiga"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
