---
title: "Raine's Reels"
---
## I Live for Cap-It-All

{{< video https://youtu.be/5LdodSpj4Vw >}}

Written by Raine Higa, directed by Dan Prior. Footage courtesy of Marguerite Butler and Marty Martinage.

“Raine’s monologue at the end of Act 1 was fantastic!”

“As a trans person in the audience, it felt incredibly vulnerable to watch such honesty of intimate thoughts that I resonate with....I felt seen and reflected in the monologue in the best way but this was also scary because the rest of the audience was also seeing these intimate thoughts that may as well have been mine....Overall this was a good discomfort and gave me lots to think about!”

## Singing Reel

{{< video https://youtu.be/qtwiAXE7ROY >}}

Video courtesy of Wellesley College.

## Shakespeare Reel

{{< video https://youtu.be/XPnYaxCWlfA >}}

## Eri Yoshida: The Pitcher Behind the "Knuckleball Princess"

{{< video https://youtu.be/EgwDIQhyN5I >}}

Written, directed, and starring Raine Higa. Filmed by Jeffrey Higa and Marguerite Butler.
